---
- hosts: localhost
  gather_facts: true
  remote_user: "{{ root }}"
  vars_files:
   - kraken_vars.yml

  tasks:
  - name: Git clone kraken repository
    git:
      repo: "https://github.com/openshift-scale/kraken.git"
      dest: "/root/kraken"
      force: yes

  - name: Generate kraken config file
    template:
      src: kraken.j2
      dest: "{{ kraken_config }}"

  - name: Start injecting failures
    shell: |
      cd "{{ kraken_dir }}"
      cp -r "{{ scenarios_folder_path }}"* scenarios/
      unset CONFIG
      python3 run_kraken.py
    ignore_errors: yes
